export const actionTypes = {
  SHOW_ALL_STUDENT: 'SHOW_ALL_STUDENT',
  ADD_STUDENT: 'ADD_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  GET_SINGLE_STUDENT: 'GET_SINGLE_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
};
